### PR TITLE
Refactored the code base and enforce persistence.

### PR DESCRIPTION
**Pull request by zhangcshcn**
Already deployed at [`nyu-promotion-service-s18.mybluemix.net`](http://nyu-promotion-service-s18.mybluemix.net)

- Refactored the code base for consistency with the lecture
- Enforce persistence when deployed
- Change the `discount_ratio` field to `Integer` (percentage) to cater to the DB
  - Our DB in the cloud performs poolly when searching using `Float`
  - Out DB is also not very capable of handling large `Integer`. Consider changing `product_id` to `String`. But it is find for now.
  - Our DB is showing wired behavior on the `primary key`. Instead of growing `1` at a time, it grows `10`

Glitch: The service may lose connection with the DB after a period of silence.

### CODE REVIEW

**Review by Marcus9527 — APPROVED** [review]

**Comment by zhangcshcn** [comment]
IBM Cloud [toolchain](https://console.ng.bluemix.net/devops/toolchains/f77b7ff7-71fd-473a-96f8-72adbfff7559?env_id=ibm%3Ayp%3Aus-south "nyu-promotion-service-s18-toolchain"): [Delivery Pipeline](https://console.ng.bluemix.net/devops/pipelines/09b4e6e6-c759-4296-b4a5-9cda76106efb?env_id=ibm%3Ayp%3Aus-south "nyu-promotion-service-s18-pipeline") deployed [promotions](https://github.com/DevOps2018-Promotions/promotions/releases/tag/deploy-ibm-yp-us-south-nyu-promotion-s18-dev-20180420-211121 "deploy-ibm-yp-us-south-nyu-promotion-s18-dev-20180420-211121") to [dev](https://console.bluemix.net/apps/4fced16b-86d0-4031-b439-b7dbf5413cc1?env_id=ibm:yp:us-south "ibm:yp:us-south:nyu-promotion-s18:dev"), including commit 2e3fcb30a493dab2144ac3a22773fbd817f60c87

**Comment by zhangcshcn** [comment]
IBM Cloud [toolchain](https://console.ng.bluemix.net/devops/toolchains/f77b7ff7-71fd-473a-96f8-72adbfff7559?env_id=ibm%3Ayp%3Aus-south "nyu-promotion-service-s18-toolchain"): [Delivery Pipeline](https://console.ng.bluemix.net/devops/pipelines/09b4e6e6-c759-4296-b4a5-9cda76106efb?env_id=ibm%3Ayp%3Aus-south "nyu-promotion-service-s18-pipeline") deployed [promotions](https://github.com/DevOps2018-Promotions/promotions/releases/tag/deploy-ibm-yp-us-south-nyu-promotion-s18-dev-20180420-222533 "deploy-ibm-yp-us-south-nyu-promotion-s18-dev-20180420-222533") to [dev](https://console.bluemix.net/apps/4fced16b-86d0-4031-b439-b7dbf5413cc1?env_id=ibm:yp:us-south "ibm:yp:us-south:nyu-promotion-s18:dev"), including commit 2e3fcb30a493dab2144ac3a22773fbd817f60c87

**Comment by zhangcshcn** [comment]
IBM Cloud [toolchain](https://console.ng.bluemix.net/devops/toolchains/f77b7ff7-71fd-473a-96f8-72adbfff7559?env_id=ibm%3Ayp%3Aus-south "nyu-promotion-service-s18-toolchain"): [Delivery Pipeline](https://console.ng.bluemix.net/devops/pipelines/09b4e6e6-c759-4296-b4a5-9cda76106efb?env_id=ibm%3Ayp%3Aus-south "nyu-promotion-service-s18-pipeline") deployed [promotions](https://github.com/DevOps2018-Promotions/promotions/releases/tag/deploy-ibm-yp-us-south-nyu-promotion-s18-prod-20180425-043209 "deploy-ibm-yp-us-south-nyu-promotion-s18-prod-20180425-043209") to [prod](https://console.bluemix.net/apps/a1afc4c3-38a5-484a-9366-2015d660dd58?env_id=ibm:yp:us-south "ibm:yp:us-south:nyu-promotion-s18:prod"), including commit 2e3fcb30a493dab2144ac3a22773fbd817f60c87

**Comment by zhangcshcn** [comment]
IBM Cloud [toolchain](https://console.ng.bluemix.net/devops/toolchains/f77b7ff7-71fd-473a-96f8-72adbfff7559?env_id=ibm%3Ayp%3Aus-south "nyu-promotion-service-s18-toolchain"): [Delivery Pipeline](https://console.ng.bluemix.net/devops/pipelines/09b4e6e6-c759-4296-b4a5-9cda76106efb?env_id=ibm%3Ayp%3Aus-south "nyu-promotion-service-s18-pipeline") deployed [promotions](https://github.com/DevOps2018-Promotions/promotions/releases/tag/deploy-ibm-yp-us-south-nyu-promotion-s18-dev-20180502-165346 "deploy-ibm-yp-us-south-nyu-promotion-s18-dev-20180502-165346") to [dev](https://console.bluemix.net/apps/4fced16b-86d0-4031-b439-b7dbf5413cc1?env_id=ibm:yp:us-south "ibm:yp:us-south:nyu-promotion-s18:dev"), including commit 2e3fcb30a493dab2144ac3a22773fbd817f60c87

**Comment by zhangcshcn** [comment]
IBM Cloud [toolchain](https://console.ng.bluemix.net/devops/toolchains/f77b7ff7-71fd-473a-96f8-72adbfff7559?env_id=ibm%3Ayp%3Aus-south "nyu-promotion-service-s18-toolchain"): [Delivery Pipeline](https://console.ng.bluemix.net/devops/pipelines/09b4e6e6-c759-4296-b4a5-9cda76106efb?env_id=ibm%3Ayp%3Aus-south "nyu-promotion-service-s18-pipeline") deployed [promotions](https://github.com/DevOps2018-Promotions/promotions/releases/tag/deploy-ibm-yp-us-south-nyu-promotion-s18-dev-20180502-170127 "deploy-ibm-yp-us-south-nyu-promotion-s18-dev-20180502-170127") to [dev](https://console.bluemix.net/apps/4fced16b-86d0-4031-b439-b7dbf5413cc1?env_id=ibm:yp:us-south "ibm:yp:us-south:nyu-promotion-s18:dev"), including commit 2e3fcb30a493dab2144ac3a22773fbd817f60c87

**Comment by zhangcshcn** [comment]
IBM Cloud [toolchain](https://console.ng.bluemix.net/devops/toolchains/f77b7ff7-71fd-473a-96f8-72adbfff7559?env_id=ibm%3Ayp%3Aus-south "nyu-promotion-service-s18-toolchain"): [Delivery Pipeline](https://console.ng.bluemix.net/devops/pipelines/09b4e6e6-c759-4296-b4a5-9cda76106efb?env_id=ibm%3Ayp%3Aus-south "nyu-promotion-service-s18-pipeline") deployed [promotions](https://github.com/DevOps2018-Promotions/promotions/releases/tag/deploy-ibm-yp-us-south-nyu-promotion-s18-dev-20180502-170822 "deploy-ibm-yp-us-south-nyu-promotion-s18-dev-20180502-170822") to [dev](https://console.bluemix.net/apps/4fced16b-86d0-4031-b439-b7dbf5413cc1?env_id=ibm:yp:us-south "ibm:yp:us-south:nyu-promotion-s18:dev"), including commit 2e3fcb30a493dab2144ac3a22773fbd817f60c87

**Comment by zhangcshcn** [comment]
IBM Cloud [toolchain](https://console.ng.bluemix.net/devops/toolchains/f77b7ff7-71fd-473a-96f8-72adbfff7559?env_id=ibm%3Ayp%3Aus-south "nyu-promotion-service-s18-toolchain"): [Delivery Pipeline](https://console.ng.bluemix.net/devops/pipelines/09b4e6e6-c759-4296-b4a5-9cda76106efb?env_id=ibm%3Ayp%3Aus-south "nyu-promotion-service-s18-pipeline") deployed [promotions](https://github.com/DevOps2018-Promotions/promotions/releases/tag/deploy-ibm-yp-us-south-nyu-promotion-s18-dev-20180502-171507 "deploy-ibm-yp-us-south-nyu-promotion-s18-dev-20180502-171507") to [dev](https://console.bluemix.net/apps/4fced16b-86d0-4031-b439-b7dbf5413cc1?env_id=ibm:yp:us-south "ibm:yp:us-south:nyu-promotion-s18:dev"), including commit 2e3fcb30a493dab2144ac3a22773fbd817f60c87

**Comment by zhangcshcn** [comment]
IBM Cloud [toolchain](https://console.ng.bluemix.net/devops/toolchains/f77b7ff7-71fd-473a-96f8-72adbfff7559?env_id=ibm%3Ayp%3Aus-south "nyu-promotion-service-s18-toolchain"): [Delivery Pipeline](https://console.ng.bluemix.net/devops/pipelines/09b4e6e6-c759-4296-b4a5-9cda76106efb?env_id=ibm%3Ayp%3Aus-south "nyu-promotion-service-s18-pipeline") deployed [promotions](https://github.com/DevOps2018-Promotions/promotions/releases/tag/deploy-ibm-yp-us-south-nyu-promotion-s18-dev-20180502-173142 "deploy-ibm-yp-us-south-nyu-promotion-s18-dev-20180502-173142") to [dev](https://console.bluemix.net/apps/4fced16b-86d0-4031-b439-b7dbf5413cc1?env_id=ibm:yp:us-south "ibm:yp:us-south:nyu-promotion-s18:dev"), including commit 2e3fcb30a493dab2144ac3a22773fbd817f60c87

**Comment by zhangcshcn** [comment]
IBM Cloud [toolchain](https://console.ng.bluemix.net/devops/toolchains/f77b7ff7-71fd-473a-96f8-72adbfff7559?env_id=ibm%3Ayp%3Aus-south "nyu-promotion-service-s18-toolchain"): [Delivery Pipeline](https://console.ng.bluemix.net/devops/pipelines/09b4e6e6-c759-4296-b4a5-9cda76106efb?env_id=ibm%3Ayp%3Aus-south "nyu-promotion-service-s18-pipeline") deployed [promotions](https://github.com/DevOps2018-Promotions/promotions/releases/tag/deploy-ibm-yp-us-south-nyu-promotion-s18-prod-20180502-180511 "deploy-ibm-yp-us-south-nyu-promotion-s18-prod-20180502-180511") to [prod](https://console.bluemix.net/apps/a1afc4c3-38a5-484a-9366-2015d660dd58?env_id=ibm:yp:us-south "ibm:yp:us-south:nyu-promotion-s18:prod"), including commit 2e3fcb30a493dab2144ac3a22773fbd817f60c87

**Pull request merged**
